"""empty message

Revision ID: 5bfd543addc
Revises: 2e32e818ef03
Create Date: 2014-03-24 10:47:22.264896

"""

# revision identifiers, used by Alembic.
revision = '5bfd543addc'
down_revision = '2e32e818ef03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
